#include "core/DrawingCore.h"

#include <QCoreApplication>
#include <QVariantList>
#include <QVariantMap>

#include <cassert>
#include <cmath>
#include <limits>

namespace {

bool nearlyEqual(double a, double b)
{
    return std::abs(a - b) < 0.000001;
}

} // namespace

int main(int argc, char **argv)
{
    QCoreApplication app(argc, argv);

    DrawingDocumentController controller;
    QVariantMap initial = controller.modelDocument();
    assert(initial.value("engine").toString() == "cpp_drafting_document");
    assert(initial.value("drawing_objects").toList().empty());
    QVariantMap initialGrid = initial.value("grid").toMap();
    assert(initialGrid.value("preset").toString() == "square_art_board");
    assert(initialGrid.value("unit_label").toString() == "in");
    assert(!initialGrid.value("lines").toList().empty());
    assert(!controller.gridSnapEnabled());
    assert(!controller.objectSnapEnabled());
    QVariantMap initialSnap = initial.value("snap").toMap();
    assert(initialSnap.value("endpoint_enabled").toBool());
    assert(initialSnap.value("vertex_enabled").toBool());
    assert(initialSnap.value("midpoint_enabled").toBool());
    assert(initialSnap.value("center_enabled").toBool());
    assert(initialSnap.value("object_priority_before_grid").toBool());
    assert(controller.objectSnapTolerancePresetId() == "normal");

    controller.setEndpointSnapEnabled(false);
    controller.setVertexSnapEnabled(false);
    controller.setMidpointSnapEnabled(false);
    controller.setCenterSnapEnabled(false);
    controller.setObjectSnapPriorityBeforeGrid(false);
    controller.setObjectSnapTolerancePreset("tight");
    QVariantMap changedSnap = controller.modelDocument().value("snap").toMap();
    assert(!controller.endpointSnapEnabled());
    assert(!controller.vertexSnapEnabled());
    assert(!controller.midpointSnapEnabled());
    assert(!controller.centerSnapEnabled());
    assert(!controller.objectSnapPriorityBeforeGrid());
    assert(controller.objectSnapTolerancePresetId() == "tight");
    assert(!changedSnap.value("endpoint_enabled").toBool());
    assert(!changedSnap.value("vertex_enabled").toBool());
    assert(!changedSnap.value("midpoint_enabled").toBool());
    assert(!changedSnap.value("center_enabled").toBool());
    assert(!changedSnap.value("object_priority_before_grid").toBool());
    assert(nearlyEqual(changedSnap.value("object_tolerance").toDouble(), 0.015));
    controller.setEndpointSnapEnabled(true);
    controller.setVertexSnapEnabled(true);
    controller.setMidpointSnapEnabled(true);
    controller.setCenterSnapEnabled(true);
    controller.setObjectSnapPriorityBeforeGrid(true);
    controller.setObjectSnapTolerancePreset("normal");

    controller.setSelectedToolId("point_tool");
    controller.clickCanvasNormalized(0.25, 0.5);
    QVariantList objects = controller.modelDocument().value("drawing_objects").toList();
    assert(objects.size() == 1);
    QVariantMap point = objects.front().toMap();
    assert(point.value("kind").toString() == "point");
    assert(point.value("x").toDouble() == 0.25);
    assert(point.value("y").toDouble() == 0.5);
    assert(point.value("layer_id").toString() == "default");
    assert(!point.value("locked").toBool());
    QVariantMap pointBounds = point.value("bounds").toMap();
    assert(pointBounds.value("x").toDouble() == 0.25);
    assert(pointBounds.value("y").toDouble() == 0.5);
    assert(pointBounds.value("width").toDouble() == 0.0);
    assert(pointBounds.value("height").toDouble() == 0.0);
    QVariantList pointMeasurement = point.value("measurement_lines").toList();
    assert(pointMeasurement.size() == 2);
    assert(pointMeasurement[0].toString() == "width: 0 canvas_unit");
    assert(pointMeasurement[1].toString() == "height: 0 canvas_unit");
    assert(controller.selectedObjectId() == point.value("id").toString());
    assert(controller.updateSelectedObjectGeometryField("x", 0.3));
    assert(controller.updateSelectedObjectGeometryField("y", 0.35));
    QVariantMap editedPoint = controller.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(editedPoint.value("x").toDouble(), 0.3));
    assert(nearlyEqual(editedPoint.value("y").toDouble(), 0.35));
    assert(!controller.updateSelectedObjectGeometryField("missing_field", 0.1));

    controller.setGridPresetId("letter");
    QVariantMap letterModel = controller.modelDocument();
    QVariantMap letterGrid = letterModel.value("grid").toMap();
    assert(controller.gridPresetId() == "letter");
    assert(letterGrid.value("preset").toString() == "letter");
    assert(letterGrid.value("unit_label").toString() == "in");
    assert(nearlyEqual(letterGrid.value("width").toDouble(), 8.5));
    assert(nearlyEqual(letterGrid.value("height").toDouble(), 11.0));
    QVariantMap letterSnap = letterModel.value("snap").toMap();
    assert(nearlyEqual(letterSnap.value("grid_step_x").toDouble(), 0.25 / 8.5));
    assert(nearlyEqual(letterSnap.value("grid_step_y").toDouble(), 0.25 / 11.0));

    controller.setSelectedToolId("line_tool");
    controller.clickCanvasNormalized(0.1, 0.2);
    assert(controller.modelDocument().value("drawing_objects").toList().size() == 1);
    controller.clickCanvasNormalized(0.8, 0.9);
    objects = controller.modelDocument().value("drawing_objects").toList();
    assert(objects.size() == 2);
    QVariantMap line = objects.back().toMap();
    assert(line.value("kind").toString() == "line");
    assert(line.value("x1").toDouble() == 0.1);
    assert(line.value("y1").toDouble() == 0.2);
    assert(line.value("x2").toDouble() == 0.8);
    assert(line.value("y2").toDouble() == 0.9);
    QVariantMap lineBounds = line.value("bounds").toMap();
    assert(nearlyEqual(lineBounds.value("x").toDouble(), 0.1));
    assert(nearlyEqual(lineBounds.value("y").toDouble(), 0.2));
    assert(nearlyEqual(lineBounds.value("width").toDouble(), 0.7));
    assert(nearlyEqual(lineBounds.value("height").toDouble(), 0.7));
    QVariantList lineMeasurement = line.value("measurement_lines").toList();
    assert(lineMeasurement.size() == 3);
    assert(lineMeasurement[0].toString().startsWith("distance: "));
    assert(lineMeasurement[1].toString().startsWith("width: "));
    assert(lineMeasurement[2].toString().startsWith("height: "));

    controller.setSelectedToolId("select_move");
    controller.clickCanvasNormalized(0.3, 0.35);
    assert(controller.selectedObjectId() == point.value("id").toString());

    controller.clickCanvasNormalized(0.8, 0.9);
    assert(controller.selectedObjectId() == line.value("id").toString());
    assert(controller.editSelectedHandleNormalized("line_end", 0.4, 0.6));
    objects = controller.modelDocument().value("drawing_objects").toList();
    QVariantMap editedLine;
    for (const QVariant &objectValue : objects) {
        const QVariantMap object = objectValue.toMap();
        if (object.value("id").toString() == line.value("id").toString()) {
            editedLine = object;
        }
    }
    assert(!editedLine.isEmpty());
    assert(editedLine.value("x2").toDouble() == 0.4);
    assert(editedLine.value("y2").toDouble() == 0.6);
    assert(!controller.editSelectedHandleNormalized("missing_handle", 0.1, 0.1));
    assert(controller.updateSelectedObjectGeometryField("x2", 0.7));
    assert(controller.updateSelectedObjectGeometryField("y2", 0.8));
    objects = controller.modelDocument().value("drawing_objects").toList();
    QVariantMap numericallyEditedLine;
    for (const QVariant &objectValue : objects) {
        const QVariantMap object = objectValue.toMap();
        if (object.value("id").toString() == line.value("id").toString()) {
            numericallyEditedLine = object;
        }
    }
    assert(!numericallyEditedLine.isEmpty());
    assert(nearlyEqual(numericallyEditedLine.value("x2").toDouble(), 0.7));
    assert(nearlyEqual(numericallyEditedLine.value("y2").toDouble(), 0.8));
    QVariantMap numericLineBounds = numericallyEditedLine.value("bounds").toMap();
    assert(nearlyEqual(numericLineBounds.value("width").toDouble(), 0.6));
    assert(!controller.updateSelectedObjectGeometryField("missing_field", 0.1));
    assert(!controller.updateSelectedObjectGeometryField("x2", std::numeric_limits<double>::infinity()));

    assert(controller.moveSelectionNormalized(0.1, -0.2));
    objects = controller.modelDocument().value("drawing_objects").toList();
    QVariantMap movedLine;
    for (const QVariant &objectValue : objects) {
        const QVariantMap object = objectValue.toMap();
        if (object.value("id").toString() == line.value("id").toString()) {
            movedLine = object;
        }
    }
    assert(!movedLine.isEmpty());
    assert(nearlyEqual(movedLine.value("x1").toDouble(), 0.2));
    assert(nearlyEqual(movedLine.value("y1").toDouble(), 0.0));
    assert(nearlyEqual(movedLine.value("x2").toDouble(), 0.8));
    assert(nearlyEqual(movedLine.value("y2").toDouble(), 0.6));

    assert(controller.offsetSelectedObject("left"));
    objects = controller.modelDocument().value("drawing_objects").toList();
    assert(objects.size() == 3);
    QVariantMap offsetLine = objects.back().toMap();
    assert(offsetLine.value("kind").toString() == "line");
    assert(controller.selectedObjectId() == offsetLine.value("id").toString());
    assert(nearlyEqual(offsetLine.value("x1").toDouble(), 0.1646446609));
    assert(nearlyEqual(offsetLine.value("y1").toDouble(), 0.0353553391));
    assert(nearlyEqual(offsetLine.value("x2").toDouble(), 0.7646446609));
    assert(nearlyEqual(offsetLine.value("y2").toDouble(), 0.6353553391));

    assert(controller.mirrorSelectedObject("vertical"));
    objects = controller.modelDocument().value("drawing_objects").toList();
    assert(objects.size() == 4);
    QVariantMap mirroredLine = objects.back().toMap();
    assert(mirroredLine.value("kind").toString() == "line");
    assert(controller.selectedObjectId() == mirroredLine.value("id").toString());
    assert(nearlyEqual(mirroredLine.value("x1").toDouble(), 0.7646446609));
    assert(nearlyEqual(mirroredLine.value("y1").toDouble(), 0.0353553391));
    assert(nearlyEqual(mirroredLine.value("x2").toDouble(), 0.1646446609));
    assert(nearlyEqual(mirroredLine.value("y2").toDouble(), 0.6353553391));

    assert(controller.repeatSelectedObject("x"));
    objects = controller.modelDocument().value("drawing_objects").toList();
    assert(objects.size() == 7);
    QVariantMap repeatedLine1 = objects[4].toMap();
    QVariantMap repeatedLine3 = objects[6].toMap();
    assert(repeatedLine1.value("kind").toString() == "line");
    assert(nearlyEqual(repeatedLine1.value("x1").toDouble(), 0.8646446609));
    assert(nearlyEqual(repeatedLine1.value("y1").toDouble(), 0.0353553391));
    assert(nearlyEqual(repeatedLine1.value("x2").toDouble(), 0.2646446609));
    assert(nearlyEqual(repeatedLine3.value("x1").toDouble(), 1.0646446609));
    assert(nearlyEqual(repeatedLine3.value("x2").toDouble(), 0.4646446609));
    QVariantList repeatedSelection = controller.modelDocument().value("selected_object_ids").toList();
    assert(repeatedSelection.size() == 3);
    assert(!controller.repeatSelectedObject("diagonal"));
    assert(controller.modelDocument().value("drawing_objects").toList().size() == 7);

    controller.clickCanvasNormalized(0.3, 0.35);
    const int beforeUnsupportedOffsetCount = controller.modelDocument().value("drawing_objects").toList().size();
    assert(!controller.offsetSelectedObject("right"));
    assert(controller.modelDocument().value("drawing_objects").toList().size() == beforeUnsupportedOffsetCount);
    assert(controller.mirrorSelectedObject("horizontal"));
    objects = controller.modelDocument().value("drawing_objects").toList();
    assert(objects.size() == beforeUnsupportedOffsetCount + 1);
    QVariantMap mirroredPoint = objects.back().toMap();
    assert(mirroredPoint.value("kind").toString() == "point");
    assert(nearlyEqual(mirroredPoint.value("x").toDouble(), 0.3));
    assert(nearlyEqual(mirroredPoint.value("y").toDouble(), 0.35));
    assert(!controller.moveSelectionNormalized(std::numeric_limits<double>::infinity(), 0.0));

    DrawingDocumentController gridController;
    gridController.setGridSnapEnabled(true);
    assert(gridController.gridSnapEnabled());
    gridController.setSelectedToolId("point_tool");
    gridController.clickCanvasNormalized(0.14, 0.14);
    QVariantMap gridPoint = gridController.modelDocument().value("drawing_objects").toList().front().toMap();
    const double squareQuarterInchStep = 0.25 / 12.0;
    const double snappedSquarePoint = 7.0 * squareQuarterInchStep;
    assert(nearlyEqual(gridPoint.value("x").toDouble(), snappedSquarePoint));
    assert(nearlyEqual(gridPoint.value("y").toDouble(), snappedSquarePoint));

    DrawingDocumentController guideController;
    guideController.setSelectedToolId("horizontal_guide_tool");
    guideController.clickCanvasNormalized(0.2, 0.3);
    guideController.setSelectedToolId("vertical_guide_tool");
    guideController.clickCanvasNormalized(0.6, 0.7);
    QVariantList guideObjects = guideController.modelDocument().value("drawing_objects").toList();
    assert(guideObjects.size() == 2);
    QVariantMap horizontalGuide = guideObjects[0].toMap();
    QVariantMap verticalGuide = guideObjects[1].toMap();
    assert(horizontalGuide.value("kind").toString() == "guide");
    assert(horizontalGuide.value("orientation").toString() == "horizontal");
    assert(nearlyEqual(horizontalGuide.value("position").toDouble(), 0.3));
    assert(!horizontalGuide.value("plot_ready").toBool());
    assert(verticalGuide.value("orientation").toString() == "vertical");
    assert(nearlyEqual(verticalGuide.value("position").toDouble(), 0.6));
    assert(guideController.updateSelectedObjectGeometryField("position", 0.8));
    guideObjects = guideController.modelDocument().value("drawing_objects").toList();
    verticalGuide = guideObjects[1].toMap();
    assert(nearlyEqual(verticalGuide.value("position").toDouble(), 0.8));
    const int guideRevisionBeforeInvalid = guideController.modelDocument().value("revision").toInt();
    assert(!guideController.updateSelectedObjectGeometryField("position", 1.2));
    assert(guideController.modelDocument().value("revision").toInt() == guideRevisionBeforeInvalid);

    DrawingDocumentController constructionController;
    constructionController.setSelectedToolId("horizontal_construction_line_tool");
    constructionController.clickCanvasNormalized(0.2, 0.3);
    constructionController.setSelectedToolId("vertical_construction_line_tool");
    constructionController.clickCanvasNormalized(0.6, 0.7);
    QVariantList constructionObjects = constructionController.modelDocument().value("drawing_objects").toList();
    assert(constructionObjects.size() == 2);
    QVariantMap horizontalConstruction = constructionObjects[0].toMap();
    QVariantMap verticalConstruction = constructionObjects[1].toMap();
    assert(horizontalConstruction.value("kind").toString() == "construction_line");
    assert(nearlyEqual(horizontalConstruction.value("x1").toDouble(), 0.0));
    assert(nearlyEqual(horizontalConstruction.value("y1").toDouble(), 0.3));
    assert(nearlyEqual(horizontalConstruction.value("x2").toDouble(), 1.0));
    assert(nearlyEqual(horizontalConstruction.value("y2").toDouble(), 0.3));
    assert(!horizontalConstruction.value("plot_ready").toBool());
    assert(nearlyEqual(verticalConstruction.value("x1").toDouble(), 0.6));
    assert(nearlyEqual(verticalConstruction.value("y1").toDouble(), 0.0));
    assert(nearlyEqual(verticalConstruction.value("x2").toDouble(), 0.6));
    assert(nearlyEqual(verticalConstruction.value("y2").toDouble(), 1.0));
    assert(constructionController.selectedObjectId() == verticalConstruction.value("id").toString());
    assert(constructionController.offsetSelectedObject("left"));
    constructionObjects = constructionController.modelDocument().value("drawing_objects").toList();
    assert(constructionObjects.size() == 3);
    QVariantMap offsetConstruction = constructionObjects.back().toMap();
    assert(offsetConstruction.value("kind").toString() == "construction_line");
    assert(nearlyEqual(offsetConstruction.value("x1").toDouble(), 0.55));
    assert(nearlyEqual(offsetConstruction.value("y1").toDouble(), 0.0));
    assert(nearlyEqual(offsetConstruction.value("x2").toDouble(), 0.55));
    assert(nearlyEqual(offsetConstruction.value("y2").toDouble(), 1.0));
    assert(constructionController.mirrorSelectedObject("horizontal"));
    constructionObjects = constructionController.modelDocument().value("drawing_objects").toList();
    assert(constructionObjects.size() == 4);
    QVariantMap mirroredConstruction = constructionObjects.back().toMap();
    assert(mirroredConstruction.value("kind").toString() == "construction_line");
    assert(nearlyEqual(mirroredConstruction.value("x1").toDouble(), 0.55));
    assert(nearlyEqual(mirroredConstruction.value("y1").toDouble(), 1.0));
    assert(nearlyEqual(mirroredConstruction.value("x2").toDouble(), 0.55));
    assert(nearlyEqual(mirroredConstruction.value("y2").toDouble(), 0.0));

    assert(constructionController.repeatSelectedObject("y"));
    constructionObjects = constructionController.modelDocument().value("drawing_objects").toList();
    assert(constructionObjects.size() == 7);
    QVariantMap repeatedConstruction = constructionObjects.back().toMap();
    assert(repeatedConstruction.value("kind").toString() == "construction_line");
    assert(nearlyEqual(repeatedConstruction.value("x1").toDouble(), 0.55));
    assert(nearlyEqual(repeatedConstruction.value("y1").toDouble(), 1.3));
    assert(nearlyEqual(repeatedConstruction.value("x2").toDouble(), 0.55));
    assert(nearlyEqual(repeatedConstruction.value("y2").toDouble(), 0.3));

    DrawingDocumentController angledConstructionController;
    angledConstructionController.setSelectedToolId("angled_construction_line_tool");
    angledConstructionController.clickCanvasNormalized(0.1, 0.2);
    angledConstructionController.updateCreationPreviewNormalized(0.7, 0.4);
    QVariantMap angledPreview = angledConstructionController.modelDocument().value("preview_object").toMap();
    assert(!angledPreview.isEmpty());
    assert(angledPreview.value("kind").toString() == "construction_line");
    assert(!angledPreview.value("plot_ready").toBool());
    assert(nearlyEqual(angledPreview.value("x1").toDouble(), 0.1));
    assert(nearlyEqual(angledPreview.value("y1").toDouble(), 0.2));
    assert(nearlyEqual(angledPreview.value("x2").toDouble(), 0.7));
    assert(nearlyEqual(angledPreview.value("y2").toDouble(), 0.4));
    assert(angledConstructionController.modelDocument().value("drawing_objects").toList().isEmpty());
    angledConstructionController.clickCanvasNormalized(0.7, 0.4);
    QVariantMap angledModel = angledConstructionController.modelDocument();
    assert(!angledModel.contains("preview_object"));
    QVariantList angledObjects = angledModel.value("drawing_objects").toList();
    assert(angledObjects.size() == 1);
    QVariantMap angledConstruction = angledObjects.front().toMap();
    assert(angledConstruction.value("kind").toString() == "construction_line");
    assert(nearlyEqual(angledConstruction.value("x1").toDouble(), 0.1));
    assert(nearlyEqual(angledConstruction.value("y1").toDouble(), 0.2));
    assert(nearlyEqual(angledConstruction.value("x2").toDouble(), 0.7));
    assert(nearlyEqual(angledConstruction.value("y2").toDouble(), 0.4));
    assert(angledConstructionController.updateSelectedObjectGeometryField("x2", 0.8));
    assert(angledConstructionController.updateSelectedObjectGeometryField("y2", 0.5));
    angledConstruction = angledConstructionController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(angledConstruction.value("x2").toDouble(), 0.8));
    assert(nearlyEqual(angledConstruction.value("y2").toDouble(), 0.5));
    assert(angledConstructionController.updateSelectedObjectGeometryField("x2", 0.1));
    const int constructionRevisionBeforeInvalid = angledConstructionController.modelDocument().value("revision").toInt();
    assert(!angledConstructionController.updateSelectedObjectGeometryField("y2", 0.2));
    assert(angledConstructionController.modelDocument().value("revision").toInt() == constructionRevisionBeforeInvalid);

    DrawingDocumentController dimensionController;
    dimensionController.setSelectedToolId("distance_dimension_tool");
    dimensionController.clickCanvasNormalized(0.1, 0.2);
    dimensionController.updateCreationPreviewNormalized(0.4, 0.6);
    QVariantMap dimensionPreview = dimensionController.modelDocument().value("preview_object").toMap();
    assert(!dimensionPreview.isEmpty());
    assert(dimensionPreview.value("kind").toString() == "dimension");
    assert(!dimensionPreview.value("plot_ready").toBool());
    assert(nearlyEqual(dimensionPreview.value("x1").toDouble(), 0.1));
    assert(nearlyEqual(dimensionPreview.value("y1").toDouble(), 0.2));
    assert(nearlyEqual(dimensionPreview.value("x2").toDouble(), 0.4));
    assert(nearlyEqual(dimensionPreview.value("y2").toDouble(), 0.6));
    assert(dimensionPreview.value("label").toString() == "0.5 canvas_unit");
    assert(dimensionController.modelDocument().value("drawing_objects").toList().isEmpty());
    dimensionController.clickCanvasNormalized(0.4, 0.6);
    QVariantMap dimensionModel = dimensionController.modelDocument();
    assert(!dimensionModel.contains("preview_object"));
    QVariantList dimensionObjects = dimensionModel.value("drawing_objects").toList();
    assert(dimensionObjects.size() == 1);
    QVariantMap dimension = dimensionObjects.front().toMap();
    assert(dimension.value("kind").toString() == "dimension");
    assert(!dimension.value("plot_ready").toBool());
    assert(dimension.value("label").toString() == "0.5 canvas_unit");
    assert(nearlyEqual(dimension.value("dimension_x1").toDouble(), 0.068));
    assert(nearlyEqual(dimension.value("dimension_y1").toDouble(), 0.224));
    assert(nearlyEqual(dimension.value("dimension_x2").toDouble(), 0.368));
    assert(nearlyEqual(dimension.value("dimension_y2").toDouble(), 0.624));
    assert(nearlyEqual(dimension.value("offset").toDouble(), 0.04));
    assert(dimensionController.updateSelectedObjectGeometryField("offset", 0.08));
    assert(dimensionController.updateSelectedObjectGeometryField("x2", 0.5));
    dimension = dimensionController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(dimension.value("offset").toDouble(), 0.08));
    assert(nearlyEqual(dimension.value("x2").toDouble(), 0.5));
    assert(dimensionController.updateSelectedObjectGeometryField("x2", 0.1));
    const int dimensionRevisionBeforeInvalid = dimensionController.modelDocument().value("revision").toInt();
    assert(!dimensionController.updateSelectedObjectGeometryField("y2", 0.2));
    assert(dimensionController.modelDocument().value("revision").toInt() == dimensionRevisionBeforeInvalid);

    DrawingDocumentController objectSnapController;
    objectSnapController.setSelectedToolId("point_tool");
    objectSnapController.clickCanvasNormalized(0.25, 0.25);
    objectSnapController.setObjectSnapEnabled(true);
    assert(objectSnapController.objectSnapEnabled());
    objectSnapController.clickCanvasNormalized(0.26, 0.24);
    QVariantList snappedObjects = objectSnapController.modelDocument().value("drawing_objects").toList();
    assert(snappedObjects.size() == 2);
    QVariantMap snappedPoint = snappedObjects.back().toMap();
    assert(nearlyEqual(snappedPoint.value("x").toDouble(), 0.25));
    assert(nearlyEqual(snappedPoint.value("y").toDouble(), 0.25));

    QVariantList beforePointerObjects = objectSnapController.modelDocument().value("drawing_objects").toList();
    objectSnapController.updatePointerNormalized(0.26, 0.24);
    QVariantMap pointerModel = objectSnapController.modelDocument();
    QVariantMap pointer = pointerModel.value("pointer").toMap();
    assert(!pointer.isEmpty());
    assert(nearlyEqual(pointer.value("raw").toMap().value("x").toDouble(), 0.26));
    assert(nearlyEqual(pointer.value("raw").toMap().value("y").toDouble(), 0.24));
    assert(pointer.value("kind").toString() == "object");
    assert(pointer.value("source").toString() == "endpoint");
    assert(nearlyEqual(pointer.value("snapped").toMap().value("x").toDouble(), 0.25));
    assert(nearlyEqual(pointer.value("snapped").toMap().value("y").toDouble(), 0.25));
    assert(nearlyEqual(pointer.value("snapped_unit_x").toDouble(), 3.0));
    assert(nearlyEqual(pointer.value("snapped_unit_y").toDouble(), 3.0));
    assert(pointer.value("unit_label").toString() == "in");
    assert(pointer.value("inside_drawable").toBool());
    assert(pointerModel.value("drawing_objects").toList().size() == beforePointerObjects.size());

    DrawingDocumentController invisibleSnapController;
    invisibleSnapController.setSelectedToolId("point_tool");
    invisibleSnapController.clickCanvasNormalized(0.25, 0.25);
    assert(invisibleSnapController.setSelectedObjectVisible(false));
    QVariantMap invisiblePoint = invisibleSnapController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(!invisiblePoint.value("visible").toBool());
    invisibleSnapController.setObjectSnapEnabled(true);
    invisibleSnapController.clickCanvasNormalized(0.26, 0.24);
    QVariantList invisibleSnapObjects = invisibleSnapController.modelDocument().value("drawing_objects").toList();
    assert(invisibleSnapObjects.size() == 2);
    QVariantMap unsnappedPoint = invisibleSnapObjects.back().toMap();
    assert(nearlyEqual(unsnappedPoint.value("x").toDouble(), 0.26));
    assert(nearlyEqual(unsnappedPoint.value("y").toDouble(), 0.24));

    DrawingDocumentController invisibleHitController;
    invisibleHitController.setSelectedToolId("point_tool");
    invisibleHitController.clickCanvasNormalized(0.25, 0.25);
    assert(invisibleHitController.setSelectedObjectVisible(false));
    invisibleHitController.setSelectedToolId("select_move");
    invisibleHitController.clickCanvasNormalized(0.25, 0.25);
    assert(invisibleHitController.selectedObjectId().isEmpty());

    DrawingDocumentController layerController;
    layerController.setSelectedToolId("point_tool");
    layerController.clickCanvasNormalized(0.25, 0.25);
    QVariantMap layerModel = layerController.modelDocument();
    QVariantList layers = layerModel.value("layers").toList();
    assert(layers.size() == 1);
    assert(layers.front().toMap().value("id").toString() == "default");
    assert(layers.front().toMap().value("visible").toBool());
    assert(!layers.front().toMap().value("locked").toBool());

    assert(layerController.setDefaultLayerVisible(false));
    layerModel = layerController.modelDocument();
    layers = layerModel.value("layers").toList();
    assert(!layers.front().toMap().value("visible").toBool());
    QVariantMap hiddenLayerPoint = layerModel.value("drawing_objects").toList().front().toMap();
    assert(hiddenLayerPoint.value("visible").toBool());
    assert(!hiddenLayerPoint.value("effective_visible").toBool());
    layerController.setObjectSnapEnabled(true);
    layerController.clickCanvasNormalized(0.26, 0.24);
    QVariantList hiddenLayerObjects = layerController.modelDocument().value("drawing_objects").toList();
    assert(hiddenLayerObjects.size() == 2);
    QVariantMap hiddenLayerUnsnappedPoint = hiddenLayerObjects.back().toMap();
    assert(nearlyEqual(hiddenLayerUnsnappedPoint.value("x").toDouble(), 0.26));
    assert(nearlyEqual(hiddenLayerUnsnappedPoint.value("y").toDouble(), 0.24));
    layerController.setSelectedToolId("select_move");
    layerController.clickCanvasNormalized(0.25, 0.25);
    assert(layerController.selectedObjectId().isEmpty());

    assert(layerController.setDefaultLayerVisible(true));
    assert(layerController.setDefaultLayerLocked(true));
    layerModel = layerController.modelDocument();
    layers = layerModel.value("layers").toList();
    assert(layers.front().toMap().value("locked").toBool());
    layerController.setSelectedToolId("point_tool");
    const int lockedLayerObjectCount = layerController.modelDocument().value("drawing_objects").toList().size();
    layerController.clickCanvasNormalized(0.5, 0.5);
    assert(layerController.modelDocument().value("drawing_objects").toList().size() == lockedLayerObjectCount);
    assert(!layerController.setSelectedObjectLocked(true));
    assert(!layerController.updateSelectedObjectGeometryField("x", 0.3));
    assert(!layerController.moveSelectionNormalized(0.1, 0.0));
    assert(layerController.setDefaultLayerLocked(false));
    layerController.clickCanvasNormalized(0.5, 0.5);
    assert(layerController.modelDocument().value("drawing_objects").toList().size() == lockedLayerObjectCount + 1);

    DrawingDocumentController layerManagementController;
    assert(layerManagementController.createLayer());
    QVariantMap layerManagementModel = layerManagementController.modelDocument();
    assert(layerManagementModel.value("active_layer_id").toString() == "layer_2");
    QVariantList managedLayers = layerManagementModel.value("layers").toList();
    assert(managedLayers.size() == 2);
    assert(layerManagementController.renameActiveLayer("Ink"));
    managedLayers = layerManagementController.modelDocument().value("layers").toList();
    assert(managedLayers[1].toMap().value("name").toString() == "Ink");
    layerManagementController.setSelectedToolId("point_tool");
    layerManagementController.clickCanvasNormalized(0.2, 0.2);
    QVariantList managedObjects = layerManagementController.modelDocument().value("drawing_objects").toList();
    assert(managedObjects.size() == 1);
    QVariantMap managedPoint = managedObjects.front().toMap();
    assert(managedPoint.value("layer_id").toString() == "layer_2");
    assert(layerManagementController.moveSelectedObjectToLayer("default"));
    managedPoint = layerManagementController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(managedPoint.value("layer_id").toString() == "default");
    assert(layerManagementController.setActiveLayerId("layer_2"));
    assert(layerManagementController.setActiveLayerLocked(true));
    const int managedObjectCountBeforeLockedCreate = layerManagementController.modelDocument().value("drawing_objects").toList().size();
    layerManagementController.clickCanvasNormalized(0.4, 0.4);
    assert(layerManagementController.modelDocument().value("drawing_objects").toList().size() == managedObjectCountBeforeLockedCreate);
    assert(layerManagementController.setActiveLayerLocked(false));
    assert(layerManagementController.setActiveLayerId("default"));
    assert(layerManagementController.setActiveLayerLocked(true));
    assert(!layerManagementController.moveSelectedObjectToLayer("layer_2"));
    assert(layerManagementController.setActiveLayerLocked(false));

    DrawingDocumentController layerOrderController;
    layerOrderController.setSelectedToolId("point_tool");
    layerOrderController.clickCanvasNormalized(0.1, 0.1);
    assert(layerOrderController.createLayer());
    assert(layerOrderController.activeLayerId() == "layer_2");
    layerOrderController.clickCanvasNormalized(0.2, 0.2);
    QVariantMap layerOrderModel = layerOrderController.modelDocument();
    QVariantList orderedLayers = layerOrderModel.value("layers").toList();
    assert(orderedLayers[0].toMap().value("id").toString() == "default");
    assert(orderedLayers[1].toMap().value("id").toString() == "layer_2");
    QVariantList orderedObjects = layerOrderModel.value("drawing_objects").toList();
    assert(orderedObjects[0].toMap().value("layer_id").toString() == "default");
    assert(orderedObjects[1].toMap().value("layer_id").toString() == "layer_2");
    assert(layerOrderController.moveActiveLayer("down"));
    layerOrderModel = layerOrderController.modelDocument();
    orderedLayers = layerOrderModel.value("layers").toList();
    assert(orderedLayers[0].toMap().value("id").toString() == "layer_2");
    assert(orderedLayers[1].toMap().value("id").toString() == "default");
    orderedObjects = layerOrderModel.value("drawing_objects").toList();
    assert(orderedObjects[0].toMap().value("layer_id").toString() == "layer_2");
    assert(orderedObjects[1].toMap().value("layer_id").toString() == "default");
    assert(!layerOrderController.moveActiveLayer("sideways"));

    DrawingDocumentController layerPlotController;
    assert(layerPlotController.createLayer());
    assert(layerPlotController.setActiveLayerPenPreset("pen_blue"));
    assert(layerPlotController.setActiveLayerStrokeWidthPreset("fine"));
    layerPlotController.setSelectedToolId("point_tool");
    layerPlotController.clickCanvasNormalized(0.2, 0.2);
    QVariantMap layerPlotModel = layerPlotController.modelDocument();
    QVariantMap layerPlotPoint = layerPlotModel.value("drawing_objects").toList().front().toMap();
    assert(layerPlotPoint.value("layer_id").toString() == "layer_2");
    assert(layerPlotPoint.value("effective_plot_enabled").toBool());
    assert(layerPlotPoint.value("effective_plot_ready").toBool());
    assert(layerPlotPoint.value("plot_ready").toBool());
    assert(layerPlotPoint.value("effective_pen_id").toString() == "pen_blue");
    assert(layerPlotPoint.value("effective_stroke_color").toString() == "#75c7ff");
    assert(nearlyEqual(layerPlotPoint.value("effective_stroke_width").toDouble(), 1.0));
    QVariantMap layerPlotSummary = layerPlotModel.value("plot_summary").toMap();
    assert(layerPlotSummary.value("order_mode").toString() == "layer_order");
    assert(layerPlotSummary.value("direction_mode").toString() == "preserve_direction");
    assert(layerPlotSummary.value("plot_object_count").toInt() == 1);
    assert(layerPlotSummary.value("segment_count").toInt() == 2);
    assert(layerPlotSummary.value("travel_segment_count").toInt() == 1);
    assert(layerPlotSummary.value("travel_distance").toDouble() > 0.0);
    QVariantList layerStats = layerPlotSummary.value("layer_stats").toList();
    assert(layerStats.size() == 1);
    QVariantMap layerStatsEntry = layerStats.front().toMap();
    assert(layerStatsEntry.value("layer_id").toString() == "layer_2");
    assert(layerStatsEntry.value("object_count").toInt() == 1);
    assert(layerStatsEntry.value("segment_count").toInt() == 2);
    assert(layerStatsEntry.value("stroke_distance").toDouble() > 0.0);
    assert(layerStatsEntry.value("travel_distance").toDouble() > 0.0);
    QVariantList penStats = layerPlotSummary.value("pen_stats").toList();
    assert(penStats.size() == 1);
    QVariantMap penStatsEntry = penStats.front().toMap();
    assert(penStatsEntry.value("pen_id").toString() == "pen_blue");
    assert(penStatsEntry.value("object_count").toInt() == 1);
    assert(penStatsEntry.value("segment_count").toInt() == 2);
    assert(penStatsEntry.value("stroke_distance").toDouble() > 0.0);
    assert(penStatsEntry.value("travel_distance").toDouble() > 0.0);
    QVariantMap layerPlotPreview = layerPlotSummary.value("preview").toMap();
    assert(layerPlotPreview.value("order_mode").toString() == "layer_order");
    assert(layerPlotPreview.value("direction_mode").toString() == "preserve_direction");
    assert(layerPlotPreview.value("segment_count").toInt() == 2);
    assert(layerPlotPreview.value("travel_segment_count").toInt() == 1);
    assert(layerPlotPreview.value("travel_distance").toDouble() > 0.0);
    assert(layerPlotPreview.value("segments").toList().size() == 2);
    const QVariantList layerPlotTravelSegments = layerPlotPreview.value("travel_segments").toList();
    assert(layerPlotTravelSegments.size() == 1);
    const QVariantMap layerPlotTravelSegment = layerPlotTravelSegments.front().toMap();
    assert(layerPlotTravelSegment.value("from_object_id").toString() == layerPlotPoint.value("id").toString());
    assert(layerPlotTravelSegment.value("to_object_id").toString() == layerPlotPoint.value("id").toString());
    assert(layerPlotTravelSegment.value("to_layer_id").toString() == "layer_2");
    assert(layerPlotTravelSegment.value("to_pen_id").toString() == "pen_blue");
    assert(layerPlotTravelSegment.value("distance").toDouble() > 0.0);
    assert(layerPlotSummary.value("warning_count").toInt() == 0);
    assert(!layerPlotSummary.value("blocked").toBool());
    assert(layerPlotController.plotOrderModeId() == "layer_order");
    layerPlotController.setPlotOrderModeId("nearest_next");
    assert(layerPlotController.plotOrderModeId() == "nearest_next");
    layerPlotSummary = layerPlotController.modelDocument().value("plot_summary").toMap();
    assert(layerPlotSummary.value("order_mode").toString() == "nearest_next");
    assert(layerPlotSummary.value("preview").toMap().value("order_mode").toString() == "nearest_next");
    layerPlotController.setPlotOrderModeId("unknown");
    assert(layerPlotController.plotOrderModeId() == "layer_order");
    assert(layerPlotController.plotDirectionModeId() == "preserve_direction");
    layerPlotController.setPlotDirectionModeId("allow_reverse_segments");
    assert(layerPlotController.plotDirectionModeId() == "allow_reverse_segments");
    layerPlotSummary = layerPlotController.modelDocument().value("plot_summary").toMap();
    assert(layerPlotSummary.value("direction_mode").toString() == "allow_reverse_segments");
    assert(layerPlotSummary.value("preview").toMap().value("direction_mode").toString() == "allow_reverse_segments");
    layerPlotController.setPlotDirectionModeId("unknown");
    assert(layerPlotController.plotDirectionModeId() == "preserve_direction");
    assert(layerPlotController.setActiveLayerPlotEnabled(false));
    layerPlotPoint = layerPlotController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(!layerPlotPoint.value("effective_plot_enabled").toBool());
    assert(!layerPlotPoint.value("effective_plot_ready").toBool());
    assert(!layerPlotPoint.value("plot_ready").toBool());
    layerPlotSummary = layerPlotController.modelDocument().value("plot_summary").toMap();
    assert(layerPlotSummary.value("plot_object_count").toInt() == 0);
    assert(layerPlotSummary.value("segment_count").toInt() == 0);
    assert(layerPlotSummary.value("layer_stats").toList().empty());
    assert(layerPlotSummary.value("pen_stats").toList().empty());
    assert(layerPlotSummary.value("travel_segment_count").toInt() == 0);
    assert(nearlyEqual(layerPlotSummary.value("travel_distance").toDouble(), 0.0));
    assert(layerPlotController.setActiveLayerPlotEnabled(true));
    layerPlotController.setSelectedToolId("horizontal_guide_tool");
    layerPlotController.clickCanvasNormalized(0.4, 0.4);
    QVariantMap layerPlotGuide = layerPlotController.modelDocument().value("drawing_objects").toList().back().toMap();
    assert(layerPlotGuide.value("kind").toString() == "guide");
    assert(layerPlotGuide.value("effective_plot_enabled").toBool());
    assert(!layerPlotGuide.value("effective_plot_ready").toBool());
    assert(!layerPlotGuide.value("plot_ready").toBool());
    layerPlotSummary = layerPlotController.modelDocument().value("plot_summary").toMap();
    assert(layerPlotSummary.value("plot_object_count").toInt() == 1);
    assert(layerPlotSummary.value("segment_count").toInt() == 2);
    assert(layerPlotSummary.value("travel_segment_count").toInt() == 1);
    layerPlotController.setSelectedToolId("point_tool");
    layerPlotController.clickCanvasNormalized(0.0, 0.0);
    layerPlotSummary = layerPlotController.modelDocument().value("plot_summary").toMap();
    assert(layerPlotSummary.value("plot_object_count").toInt() == 2);
    assert(layerPlotSummary.value("segment_count").toInt() == 4);
    assert(layerPlotSummary.value("travel_segment_count").toInt() == 3);
    assert(layerPlotSummary.value("travel_distance").toDouble() > 0.0);
    assert(layerPlotSummary.value("warning_count").toInt() == 1);
    assert(layerPlotSummary.value("blocked").toBool());
    assert(!layerPlotSummary.value("first_warning_object_id").toString().isEmpty());

    DrawingDocumentController selectionController;
    selectionController.setSelectedToolId("point_tool");
    selectionController.clickCanvasNormalized(0.1, 0.1);
    selectionController.clickCanvasNormalized(0.4, 0.4);
    selectionController.clickCanvasNormalized(0.8, 0.8);
    assert(selectionController.selectObjectsInBoundsNormalized(0.0, 0.0, 0.5, 0.5));
    QVariantMap selectionModel = selectionController.modelDocument();
    QVariantList selectedIds = selectionModel.value("selected_object_ids").toList();
    assert(selectedIds.size() == 2);
    assert(selectionModel.value("active_object_id").toString() == selectedIds.back().toString());

    DrawingDocumentController arrangeController;
    arrangeController.setSelectedToolId("point_tool");
    arrangeController.clickCanvasNormalized(0.2, 0.2);
    arrangeController.clickCanvasNormalized(0.5, 0.7);
    arrangeController.clickCanvasNormalized(0.8, 0.4);
    assert(arrangeController.selectObjectsInBoundsNormalized(0.0, 0.0, 1.0, 1.0));
    assert(arrangeController.alignSelection("left"));
    QVariantList arrangedObjects = arrangeController.modelDocument().value("drawing_objects").toList();
    assert(arrangedObjects.size() == 3);
    assert(nearlyEqual(arrangedObjects[0].toMap().value("x").toDouble(), 0.2));
    assert(nearlyEqual(arrangedObjects[1].toMap().value("x").toDouble(), 0.2));
    assert(nearlyEqual(arrangedObjects[2].toMap().value("x").toDouble(), 0.2));
    assert(!arrangeController.alignSelection("diagonal"));
    assert(arrangeController.distributeSelection("y"));
    arrangedObjects = arrangeController.modelDocument().value("drawing_objects").toList();
    assert(nearlyEqual(arrangedObjects[0].toMap().value("y").toDouble(), 0.2));
    assert(nearlyEqual(arrangedObjects[1].toMap().value("y").toDouble(), 0.7));
    assert(nearlyEqual(arrangedObjects[2].toMap().value("y").toDouble(), 0.45));
    assert(!arrangeController.distributeSelection("diagonal"));

    DrawingDocumentController previewController;
    previewController.setSelectedToolId("line_tool");
    previewController.clickCanvasNormalized(0.2, 0.2);
    QVariantMap pendingModel = previewController.modelDocument();
    assert(pendingModel.value("drawing_objects").toList().empty());
    assert(!pendingModel.contains("preview_object"));

    previewController.updateCreationPreviewNormalized(0.6, 0.7);
    QVariantMap previewModel = previewController.modelDocument();
    assert(previewModel.value("drawing_objects").toList().empty());
    assert(previewModel.contains("preview_object"));
    QVariantMap previewLine = previewModel.value("preview_object").toMap();
    assert(previewLine.value("kind").toString() == "line");
    assert(nearlyEqual(previewLine.value("x1").toDouble(), 0.2));
    assert(nearlyEqual(previewLine.value("y1").toDouble(), 0.2));
    assert(nearlyEqual(previewLine.value("x2").toDouble(), 0.6));
    assert(nearlyEqual(previewLine.value("y2").toDouble(), 0.7));

    previewController.clickCanvasNormalized(0.6, 0.7);
    QVariantMap committedPreviewModel = previewController.modelDocument();
    assert(committedPreviewModel.value("drawing_objects").toList().size() == 1);
    assert(!committedPreviewModel.contains("preview_object"));

    DrawingDocumentController cancelPreviewController;
    cancelPreviewController.setSelectedToolId("rectangle_tool");
    cancelPreviewController.clickCanvasNormalized(0.1, 0.1);
    cancelPreviewController.updateCreationPreviewNormalized(0.4, 0.4);
    assert(cancelPreviewController.modelDocument().contains("preview_object"));
    cancelPreviewController.setSelectedToolId("select_move");
    assert(!cancelPreviewController.modelDocument().contains("preview_object"));
    assert(cancelPreviewController.modelDocument().value("drawing_objects").toList().empty());

    DrawingDocumentController snappedPreviewController;
    snappedPreviewController.setGridSnapEnabled(true);
    snappedPreviewController.setSelectedToolId("rectangle_tool");
    snappedPreviewController.clickCanvasNormalized(0.14, 0.14);
    snappedPreviewController.updateCreationPreviewNormalized(0.36, 0.36);
    QVariantMap snappedPreview = snappedPreviewController.modelDocument().value("preview_object").toMap();
    assert(snappedPreview.value("kind").toString() == "rectangle");
    assert(nearlyEqual(snappedPreview.value("x").toDouble(), snappedSquarePoint));
    assert(nearlyEqual(snappedPreview.value("y").toDouble(), snappedSquarePoint));
    const double snappedSquareExtent = 10.0 * squareQuarterInchStep;
    assert(nearlyEqual(snappedPreview.value("width").toDouble(), snappedSquareExtent));
    assert(nearlyEqual(snappedPreview.value("height").toDouble(), snappedSquareExtent));
    assert(snappedPreviewController.modelDocument().value("drawing_objects").toList().empty());
    snappedPreviewController.clickCanvasNormalized(0.36, 0.36);
    QVariantMap snappedCommitted = snappedPreviewController.modelDocument();
    assert(snappedCommitted.value("drawing_objects").toList().size() == 1);
    assert(!snappedCommitted.contains("preview_object"));

    DrawingDocumentController zeroSizeController;
    zeroSizeController.setSelectedToolId("circle_tool");
    zeroSizeController.clickCanvasNormalized(0.5, 0.5);
    zeroSizeController.updateCreationPreviewNormalized(0.5, 0.5);
    QVariantMap zeroCirclePreview = zeroSizeController.modelDocument().value("preview_object").toMap();
    assert(zeroCirclePreview.value("kind").toString() == "circle");
    assert(nearlyEqual(zeroCirclePreview.value("radius").toDouble(), 0.0));
    zeroSizeController.clickCanvasNormalized(0.5, 0.5);
    QVariantMap zeroCircleCommitted = zeroSizeController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(zeroCircleCommitted.value("radius").toDouble(), 0.0));

    DrawingDocumentController numericRectController;
    numericRectController.setSelectedToolId("rectangle_tool");
    numericRectController.clickCanvasNormalized(0.1, 0.1);
    numericRectController.clickCanvasNormalized(0.4, 0.4);
    assert(numericRectController.updateSelectedObjectGeometryField("width", 0.5));
    assert(numericRectController.updateSelectedObjectGeometryField("height", 0.25));
    assert(numericRectController.updateSelectedObjectGeometryField("rotation_deg", 45.0));
    QVariantMap numericRect = numericRectController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericRect.value("width").toDouble(), 0.5));
    assert(nearlyEqual(numericRect.value("height").toDouble(), 0.25));
    assert(nearlyEqual(numericRect.value("rotation_deg").toDouble(), 45.0));
    QVariantList numericRectMeasurement = numericRect.value("measurement_lines").toList();
    assert(numericRectMeasurement.size() == 3);
    assert(numericRectMeasurement[0].toString().startsWith("area: "));
    assert(!numericRectController.updateSelectedObjectGeometryField("width", -0.1));
    QVariantMap numericRectAfterInvalid = numericRectController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericRectAfterInvalid.value("width").toDouble(), 0.5));

    DrawingDocumentController numericCircleController;
    numericCircleController.setSelectedToolId("circle_tool");
    numericCircleController.clickCanvasNormalized(0.5, 0.5);
    numericCircleController.clickCanvasNormalized(0.7, 0.5);
    assert(numericCircleController.updateSelectedObjectGeometryField("cx", 0.4));
    assert(numericCircleController.updateSelectedObjectGeometryField("cy", 0.45));
    assert(numericCircleController.updateSelectedObjectGeometryField("radius", 0.125));
    QVariantMap numericCircle = numericCircleController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericCircle.value("cx").toDouble(), 0.4));
    assert(nearlyEqual(numericCircle.value("cy").toDouble(), 0.45));
    assert(nearlyEqual(numericCircle.value("radius").toDouble(), 0.125));
    assert(nearlyEqual(numericCircle.value("diameter").toDouble(), 0.25));
    QVariantList numericCircleMeasurement = numericCircle.value("measurement_lines").toList();
    assert(numericCircleMeasurement.size() == 3);
    assert(numericCircleMeasurement[0].toString().startsWith("area: "));
    assert(numericCircleController.updateSelectedObjectGeometryField("diameter", 0.5));
    numericCircle = numericCircleController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericCircle.value("radius").toDouble(), 0.25));
    assert(nearlyEqual(numericCircle.value("diameter").toDouble(), 0.5));
    assert(!numericCircleController.updateSelectedObjectGeometryField("radius", -0.01));
    assert(!numericCircleController.updateSelectedObjectGeometryField("diameter", -0.01));
    QVariantMap numericCircleAfterInvalid = numericCircleController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericCircleAfterInvalid.value("radius").toDouble(), 0.25));
    assert(nearlyEqual(numericCircleAfterInvalid.value("diameter").toDouble(), 0.5));

    DrawingDocumentController numericLineController;
    numericLineController.setSelectedToolId("line_tool");
    numericLineController.clickCanvasNormalized(0.1, 0.2);
    numericLineController.clickCanvasNormalized(0.4, 0.6);
    QVariantMap numericLine = numericLineController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericLine.value("line_length").toDouble(), 0.5));
    assert(nearlyEqual(numericLine.value("line_angle_deg").toDouble(), 53.1301023542));
    assert(numericLineController.updateSelectedObjectGeometryField("line_length", 1.0));
    numericLine = numericLineController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericLine.value("x1").toDouble(), 0.1));
    assert(nearlyEqual(numericLine.value("y1").toDouble(), 0.2));
    assert(nearlyEqual(numericLine.value("x2").toDouble(), 0.7));
    assert(nearlyEqual(numericLine.value("y2").toDouble(), 1.0));
    assert(nearlyEqual(numericLine.value("line_length").toDouble(), 1.0));
    assert(numericLineController.updateSelectedObjectGeometryField("line_angle_deg", 0.0));
    numericLine = numericLineController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(numericLine.value("x2").toDouble(), 1.1));
    assert(nearlyEqual(numericLine.value("y2").toDouble(), 0.2));
    assert(nearlyEqual(numericLine.value("line_angle_deg").toDouble(), 0.0));
    const int lineRevisionBeforeInvalid = numericLineController.modelDocument().value("revision").toInt();
    assert(!numericLineController.updateSelectedObjectGeometryField("line_length", -0.1));
    assert(!numericLineController.updateSelectedObjectGeometryField("line_angle_deg", std::numeric_limits<double>::infinity()));
    assert(numericLineController.modelDocument().value("revision").toInt() == lineRevisionBeforeInvalid);

    DrawingDocumentController lockedLineController;
    lockedLineController.setSelectedToolId("line_tool");
    lockedLineController.clickCanvasNormalized(0.1, 0.1);
    lockedLineController.clickCanvasNormalized(0.4, 0.4);
    QVariantMap lockedLine = lockedLineController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(!lockedLine.value("locked").toBool());
    assert(lockedLine.value("visible").toBool());
    assert(lockedLineController.setSelectedObjectLocked(true));
    lockedLine = lockedLineController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(lockedLine.value("locked").toBool());
    const int lockedRevision = lockedLineController.modelDocument().value("revision").toInt();
    assert(!lockedLineController.updateSelectedObjectGeometryField("x2", 0.8));
    assert(!lockedLineController.editSelectedHandleNormalized("line_end", 0.8, 0.8));
    assert(!lockedLineController.moveSelectionNormalized(0.1, 0.0));
    assert(!lockedLineController.offsetSelectedObject("left"));
    assert(!lockedLineController.mirrorSelectedObject("vertical"));
    assert(!lockedLineController.repeatSelectedObject("x"));
    assert(lockedLineController.modelDocument().value("revision").toInt() == lockedRevision);
    assert(lockedLineController.setSelectedObjectLocked(false));
    assert(lockedLineController.updateSelectedObjectGeometryField("x2", 0.8));
    lockedLine = lockedLineController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(lockedLine.value("x2").toDouble(), 0.8));

    DrawingDocumentController noSelectionEditController;
    assert(!noSelectionEditController.updateSelectedObjectGeometryField("x", 0.2));
    assert(!noSelectionEditController.setSelectedObjectLocked(true));
    assert(!noSelectionEditController.setSelectedObjectVisible(false));
    assert(!noSelectionEditController.nudgeSelection("right", "grid"));

    DrawingDocumentController nudgeController;
    nudgeController.setSelectedToolId("point_tool");
    nudgeController.clickCanvasNormalized(0.5, 0.5);
    assert(nudgeController.nudgeSelection("right", "grid"));
    assert(nudgeController.nudgeSelection("up", "fine"));
    QVariantMap nudgedPoint = nudgeController.modelDocument().value("drawing_objects").toList().front().toMap();
    assert(nearlyEqual(nudgedPoint.value("x").toDouble(), 0.5 + squareQuarterInchStep));
    assert(nearlyEqual(nudgedPoint.value("y").toDouble(), 0.5 - squareQuarterInchStep * 0.25));
    assert(!nudgeController.nudgeSelection("diagonal", "grid"));

    DrawingDocumentController selectionIsolationController;
    selectionIsolationController.setSelectedToolId("point_tool");
    selectionIsolationController.clickCanvasNormalized(0.2, 0.2);
    QString selectedBeforePreview = selectionIsolationController.selectedObjectId();
    selectionIsolationController.setSelectedToolId("line_tool");
    selectionIsolationController.clickCanvasNormalized(0.4, 0.4);
    selectionIsolationController.updateCreationPreviewNormalized(0.8, 0.8);
    assert(selectionIsolationController.modelDocument().contains("preview_object"));
    assert(selectionIsolationController.selectedObjectId() == selectedBeforePreview);
    selectionIsolationController.setSelectedToolId("select_move");
    selectionIsolationController.clickCanvasNormalized(0.8, 0.8);
    assert(selectionIsolationController.selectedObjectId().isEmpty());

    return 0;
}
