#include "recipe/RecipeEmit.h"

#include "drafting/DraftingStore.h"

#include <cassert>
#include <string>
#include <utility>

using namespace edi::recipe;
using namespace edi::drafting;

namespace {

DraftingObject object(DraftingObjectId id, DraftingShapeKind kind, DraftingGeometry geometry)
{
    auto built = buildDraftingObject(std::move(id), kind, std::move(geometry));
    assert(built.ok);
    return built.object;
}

} // namespace

int main()
{
    // A drafting document supplying the measurements: a 0.5x0.25 plank on a
    // 12x8 physical grid (-> 6 by 2), and a 0.125-radius hole (-> 1.5).
    DraftingDocument drafting = makeDraftingDocument("emit_doc");
    assert(addObject(drafting, object("plank", DraftingShapeKind::Rectangle,
        RectangleGeometry{{0.1, 0.1}, 0.5, 0.25})).ok);
    assert(addObject(drafting, object("hole", DraftingShapeKind::Circle,
        CircleGeometry{{0.5, 0.5}, 0.125})).ok);
    DraftingGridSettings settings;
    settings.width = 12.0;
    settings.height = 8.0;
    const DraftingGridProjection grid = projectDraftingGrid(settings);

    RecipeDocument recipe;
    recipe.id = "bench_block";
    recipe.name = "Bench Block";
    assert(addShaperStep(recipe, "cube").ok);
    assert(addShaperStep(recipe, "bevel").ok);
    assert(addShaperStep(recipe, "array").ok);
    assert(bindParamToMeasurement(recipe, 0, "size_x", {"plank", "width"}).ok);
    assert(bindParamToMeasurement(recipe, 0, "size_y", {"plank", "height"}).ok);
    assert(setParamLiteral(recipe, 0, "size_z", 0.75).ok);
    assert(bindParamToMeasurement(recipe, 2, "offset_x", {"hole", "radius"}).ok);
    assert(setParamLiteral(recipe, 2, "count", 3.0).ok);

    // The golden script: byte-exact. Every number is either typed (0.75, 3,
    // bevel defaults) or measured (6, 2, 1.5) — never approximated, and the
    // measured ones are called out per step.
    const ResolvedRecipe resolved = resolveRecipe(recipe, drafting, grid);
    assert(resolved.ok);
    const RecipeEmitResult emitted = emitBlenderPython(recipe, resolved);
    assert(emitted.ok);

    const std::string expected =
        "# edi recipe: Bench Block\n"
        "# generated by edi - every number below is exact (typed or measured)\n"
        "import bpy\n"
        "import math\n"
        "\n"
        "# step 1: cube\n"
        "  # measured from canvas: size_x, size_y\n"
        "bpy.ops.mesh.primitive_cube_add(size=1.0)\n"
        "obj = bpy.context.active_object\n"
        "obj.scale = (6, 2, 0.75)\n"
        "obj.location[2] = 0.375  # base z = 0\n"
        "\n"
        "# step 2: bevel\n"
        "mod = obj.modifiers.new(name=\"Bevel\", type='BEVEL')\n"
        "mod.width = 0.05\n"
        "mod.segments = 2\n"
        "\n"
        "# step 3: array\n"
        "  # measured from canvas: offset_x\n"
        "mod = obj.modifiers.new(name=\"Array\", type='ARRAY')\n"
        "mod.count = 3\n"
        "mod.use_relative_offset = False\n"
        "mod.use_constant_offset = True\n"
        "mod.constant_offset_displace[0] = 1.5\n";
    assert(emitted.script == expected);

    // A cylinder recipe exercises the second primitive's emitter.
    RecipeDocument round;
    round.id = "dowel";
    assert(addShaperStep(round, "cylinder").ok);
    assert(bindParamToMeasurement(round, 0, "radius", {"hole", "radius"}).ok);
    const ResolvedRecipe roundResolved = resolveRecipe(round, drafting, grid);
    const RecipeEmitResult roundEmitted = emitBlenderPython(round, roundResolved);
    assert(roundEmitted.ok);
    assert(roundEmitted.script.find("primitive_cylinder_add(radius=1.5, depth=1)") != std::string::npos);
    assert(roundEmitted.script.find("# edi recipe: dowel\n") != std::string::npos); // id fallback when unnamed

    // Multi-part recipes: a second primitive starts a NEW part (obj rebinds
    // in the script), each placed by its own loc_z; a modifier after it
    // shapes the most recent part. This is how an assembly like a column
    // stacks: every part's base is a pointable number.
    {
        RecipeDocument stacked;
        stacked.id = "stack";
        assert(addShaperStep(stacked, "cube").ok);
        assert(setParamLiteral(stacked, 0, "size_z", 0.5).ok);
        assert(addShaperStep(stacked, "cylinder").ok);
        assert(setParamLiteral(stacked, 1, "loc_z", 0.5).ok); // sits ON the cube
        assert(setParamLiteral(stacked, 1, "depth", 2.0).ok);
        assert(addShaperStep(stacked, "bevel").ok); // shapes the cylinder, not the cube
        const ResolvedRecipe stackedResolved = resolveRecipe(stacked, drafting, grid);
        assert(stackedResolved.ok);
        const RecipeEmitResult stackedEmitted = emitBlenderPython(stacked, stackedResolved);
        assert(stackedEmitted.ok);
        // Two parts, two rebinds; the cylinder centre = 0.5 + 2/2 = 1.5.
        std::size_t rebinds = 0;
        for (std::size_t at = stackedEmitted.script.find("obj = bpy.context.active_object");
             at != std::string::npos;
             at = stackedEmitted.script.find("obj = bpy.context.active_object", at + 1)) {
            ++rebinds;
        }
        assert(rebinds == 2);
        assert(stackedEmitted.script.find("obj.location[2] = 1.5  # base z = 0.5") != std::string::npos);
        // The bevel block comes AFTER the cylinder's rebind — linear emission
        // means "most recent part" needs no bookkeeping at all.
        assert(stackedEmitted.script.find("type='BEVEL'") > stackedEmitted.script.rfind("obj = bpy.context.active_object"));
    }

    // Lathe: the drafted profile's exact physical coordinates land verbatim
    // in the vertex table; the SCREW modifier is the lathe. %.9g printing
    // absorbs double noise, so 0.105*12 reads exactly "1.26".
    {
        DraftingDocument profileDoc = makeDraftingDocument("profiles");
        PolylineGeometry shaftProfile;
        shaftProfile.vertices = {{0.105, 0.90}, {0.085, 0.20}};
        assert(addObject(profileDoc, object("shaft", DraftingShapeKind::Polyline, shaftProfile)).ok);

        RecipeDocument turned;
        turned.id = "turned";
        assert(addShaperStep(turned, "lathe").ok);
        assert(setStepProfile(turned, 0, "shaft").ok);
        assert(addShaperStep(turned, "radial_groove").ok);
        assert(setParamLiteral(turned, 1, "count", 20.0).ok);
        assert(setParamLiteral(turned, 1, "cutter_radius", 0.15).ok);
        assert(setParamLiteral(turned, 1, "depth", 0.07).ok);
        assert(setParamLiteral(turned, 1, "at_radius", 1.26).ok);
        assert(setParamLiteral(turned, 1, "z_from", 1.0).ok);
        assert(setParamLiteral(turned, 1, "z_to", 6.0).ok);

        const ResolvedRecipe turnedResolved = resolveRecipe(turned, profileDoc, grid);
        assert(turnedResolved.ok);
        const RecipeEmitResult turnedEmitted = emitBlenderPython(turned, turnedResolved);
        assert(turnedEmitted.ok);
        const std::string &script = turnedEmitted.script;
        assert(script.find("mesh.from_pydata([(1.26, 0.0, 0.8), (1.02, 0.0, 6.4)], [(0, 1)], [])")
               != std::string::npos);
        assert(script.find("mod = obj.modifiers.new(name=\"Lathe\", type='SCREW')") != std::string::npos);
        assert(script.find("mod.steps = 64") != std::string::npos);
        // Grooves: 20 cutters on the exact circle, each a boolean DIFFERENCE;
        // centre distance shows its arithmetic (1.26 + 0.15 - 0.07 = 1.34).
        assert(script.find("for _i in range(20):") != std::string::npos);
        assert(script.find("_d = 1.34  # at_radius 1.26 + cutter 0.15 - depth 0.07") != std::string::npos);
        assert(script.find("primitive_cylinder_add(radius=0.15, depth=5)") != std::string::npos);
        assert(script.find("_m.operation = 'DIFFERENCE'") != std::string::npos);
        assert(script.find("_c.location = (_d * math.cos(_a), _d * math.sin(_a), 3.5)") != std::string::npos);
        // After the grooves the part is the target again: later modifiers
        // shape the grooved lathe, not the last cutter.
        assert(script.find("obj = _target") != std::string::npos);
    }

    // Emission refuses an unresolved recipe — no script with a guess in it.
    RecipeDocument stale = recipe;
    assert(bindParamToMeasurement(stale, 0, "size_z", {"gone", "width"}).ok);
    const ResolvedRecipe broken = resolveRecipe(stale, drafting, grid);
    assert(!broken.ok);
    const RecipeEmitResult refused = emitBlenderPython(stale, broken);
    assert(!refused.ok);
    assert(refused.script.empty());
    assert(!refused.message.empty());

    return 0;
}
