#include "recipe/RecipeEmit.h"

#include "drafting/DraftingStore.h"

#include <cassert>
#include <string>
#include <utility>

using namespace edi::recipe;
using namespace edi::drafting;

namespace {

DraftingObject object(DraftingObjectId id, DraftingShapeKind kind, DraftingGeometry geometry)
{
    auto built = buildDraftingObject(std::move(id), kind, std::move(geometry));
    assert(built.ok);
    return built.object;
}

} // namespace

int main()
{
    // A drafting document supplying the measurements: a 0.5x0.25 plank on a
    // 12x8 physical grid (-> 6 by 2), and a 0.125-radius hole (-> 1.5).
    DraftingDocument drafting = makeDraftingDocument("emit_doc");
    assert(addObject(drafting, object("plank", DraftingShapeKind::Rectangle,
        RectangleGeometry{{0.1, 0.1}, 0.5, 0.25})).ok);
    assert(addObject(drafting, object("hole", DraftingShapeKind::Circle,
        CircleGeometry{{0.5, 0.5}, 0.125})).ok);
    DraftingGridSettings settings;
    settings.width = 12.0;
    settings.height = 8.0;
    const DraftingGridProjection grid = projectDraftingGrid(settings);

    RecipeDocument recipe;
    recipe.id = "bench_block";
    recipe.name = "Bench Block";
    assert(addShaperStep(recipe, "cube").ok);
    assert(addShaperStep(recipe, "bevel").ok);
    assert(addShaperStep(recipe, "array").ok);
    assert(bindParamToMeasurement(recipe, 0, "size_x", {"plank", "width"}).ok);
    assert(bindParamToMeasurement(recipe, 0, "size_y", {"plank", "height"}).ok);
    assert(setParamLiteral(recipe, 0, "size_z", 0.75).ok);
    assert(bindParamToMeasurement(recipe, 2, "offset_x", {"hole", "radius"}).ok);
    assert(setParamLiteral(recipe, 2, "count", 3.0).ok);

    // The golden script: byte-exact. Every number is either typed (0.75, 3,
    // bevel defaults) or measured (6, 2, 1.5) — never approximated, and the
    // measured ones are called out per step.
    const ResolvedRecipe resolved = resolveRecipe(recipe, drafting, grid);
    assert(resolved.ok);
    const RecipeEmitResult emitted = emitBlenderPython(recipe, resolved);
    assert(emitted.ok);

    const std::string expected =
        "# edi recipe: Bench Block\n"
        "# generated by edi - every number below is exact (typed or measured)\n"
        "import bpy\n"
        "\n"
        "# step 1: cube\n"
        "  # measured from canvas: size_x, size_y\n"
        "bpy.ops.mesh.primitive_cube_add(size=1.0)\n"
        "obj = bpy.context.active_object\n"
        "obj.scale = (6, 2, 0.75)\n"
        "obj.location[2] = 0.375  # base z = 0\n"
        "\n"
        "# step 2: bevel\n"
        "mod = obj.modifiers.new(name=\"Bevel\", type='BEVEL')\n"
        "mod.width = 0.05\n"
        "mod.segments = 2\n"
        "\n"
        "# step 3: array\n"
        "  # measured from canvas: offset_x\n"
        "mod = obj.modifiers.new(name=\"Array\", type='ARRAY')\n"
        "mod.count = 3\n"
        "mod.use_relative_offset = False\n"
        "mod.use_constant_offset = True\n"
        "mod.constant_offset_displace[0] = 1.5\n";
    assert(emitted.script == expected);

    // A cylinder recipe exercises the second primitive's emitter.
    RecipeDocument round;
    round.id = "dowel";
    assert(addShaperStep(round, "cylinder").ok);
    assert(bindParamToMeasurement(round, 0, "radius", {"hole", "radius"}).ok);
    const ResolvedRecipe roundResolved = resolveRecipe(round, drafting, grid);
    const RecipeEmitResult roundEmitted = emitBlenderPython(round, roundResolved);
    assert(roundEmitted.ok);
    assert(roundEmitted.script.find("primitive_cylinder_add(radius=1.5, depth=1)") != std::string::npos);
    assert(roundEmitted.script.find("# edi recipe: dowel\n") != std::string::npos); // id fallback when unnamed

    // Multi-part recipes: a second primitive starts a NEW part (obj rebinds
    // in the script), each placed by its own loc_z; a modifier after it
    // shapes the most recent part. This is how an assembly like a column
    // stacks: every part's base is a pointable number.
    {
        RecipeDocument stacked;
        stacked.id = "stack";
        assert(addShaperStep(stacked, "cube").ok);
        assert(setParamLiteral(stacked, 0, "size_z", 0.5).ok);
        assert(addShaperStep(stacked, "cylinder").ok);
        assert(setParamLiteral(stacked, 1, "loc_z", 0.5).ok); // sits ON the cube
        assert(setParamLiteral(stacked, 1, "depth", 2.0).ok);
        assert(addShaperStep(stacked, "bevel").ok); // shapes the cylinder, not the cube
        const ResolvedRecipe stackedResolved = resolveRecipe(stacked, drafting, grid);
        assert(stackedResolved.ok);
        const RecipeEmitResult stackedEmitted = emitBlenderPython(stacked, stackedResolved);
        assert(stackedEmitted.ok);
        // Two parts, two rebinds; the cylinder centre = 0.5 + 2/2 = 1.5.
        std::size_t rebinds = 0;
        for (std::size_t at = stackedEmitted.script.find("obj = bpy.context.active_object");
             at != std::string::npos;
             at = stackedEmitted.script.find("obj = bpy.context.active_object", at + 1)) {
            ++rebinds;
        }
        assert(rebinds == 2);
        assert(stackedEmitted.script.find("obj.location[2] = 1.5  # base z = 0.5") != std::string::npos);
        // The bevel block comes AFTER the cylinder's rebind — linear emission
        // means "most recent part" needs no bookkeeping at all.
        assert(stackedEmitted.script.find("type='BEVEL'") > stackedEmitted.script.rfind("obj = bpy.context.active_object"));
    }

    // Emission refuses an unresolved recipe — no script with a guess in it.
    RecipeDocument stale = recipe;
    assert(bindParamToMeasurement(stale, 0, "size_z", {"gone", "width"}).ok);
    const ResolvedRecipe broken = resolveRecipe(stale, drafting, grid);
    assert(!broken.ok);
    const RecipeEmitResult refused = emitBlenderPython(stale, broken);
    assert(!refused.ok);
    assert(refused.script.empty());
    assert(!refused.message.empty());

    return 0;
}
