op.0.base_z = "1"
op.0.footprint.0.x = "0"
op.0.footprint.0.y = "0"
op.0.footprint.1.x = "4"
op.0.footprint.1.y = "0"
op.0.footprint.2.x = "4"
op.0.footprint.2.y = "2"
op.0.footprint.3.x = "2"
op.0.footprint.3.y = "2"
op.0.footprint.4.x = "2"
op.0.footprint.4.y = "4"
op.0.footprint.5.x = "0"
op.0.footprint.5.y = "4"
op.0.height = "3"
op.0.material = "stone"
op.0.name = "panel.l_bracket"
op.0.taper_end = "1"
op.0.type = "AddPrism"
op.0.x = "0"
op.0.y = "0"
recipe.id = "extruded_figure_v0"
recipe.name = "Extruded Figure"
