# edi recipe: Doric Column
# generated by edi - every number below is exact (typed or measured)
import bpy
import math

# step 1: cube
bpy.ops.mesh.primitive_cube_add(size=1.0)
obj = bpy.context.active_object
obj.scale = (3, 3, 0.48)
obj.location[2] = 0.24  # base z = 0

# step 2: cube
bpy.ops.mesh.primitive_cube_add(size=1.0)
obj = bpy.context.active_object
obj.scale = (2.64, 2.64, 0.36)
obj.location[2] = 0.66  # base z = 0.48

# step 3: lathe
mesh = bpy.data.meshes.new("lathe")
mesh.from_pydata([(1.32, 0.0, 0.84), (1.152, 0.0, 0.912), (1.056, 0.0, 1.008)], [(0, 1), (1, 2)], [])
obj = bpy.data.objects.new("lathe", mesh)
bpy.context.collection.objects.link(obj)
bpy.context.view_layer.objects.active = obj
mod = obj.modifiers.new(name="Lathe", type='SCREW')
mod.angle = 6.283185307179586
mod.steps = 64
mod.use_merge_vertices = True
obj.location[2] = 0  # offset from drafted height

# step 4: lathe
mesh = bpy.data.meshes.new("lathe")
mesh.from_pydata([(1.056, 0.0, 1.008), (1.032, 0.0, 3.6), (0.96, 0.0, 6), (0.84, 0.0, 7.8), (0.792, 0.0, 8.04)], [(0, 1), (1, 2), (2, 3), (3, 4)], [])
obj = bpy.data.objects.new("lathe", mesh)
bpy.context.collection.objects.link(obj)
bpy.context.view_layer.objects.active = obj
mod = obj.modifiers.new(name="Lathe", type='SCREW')
mod.angle = 6.283185307179586
mod.steps = 64
mod.use_merge_vertices = True
obj.location[2] = 0  # offset from drafted height

# step 5: radial_groove
_target = obj
for _i in range(20):
    _a = 6.283185307179586 * _i / 20
    _d = 1.096  # at_radius 1.056 + cutter 0.16 - depth 0.12
    bpy.ops.mesh.primitive_cylinder_add(radius=0.16, depth=4.8)
    _c = bpy.context.active_object
    _c.location = (_d * math.cos(_a), _d * math.sin(_a), 3.6)
    _m = _target.modifiers.new(name="Groove", type='BOOLEAN')
    _m.operation = 'DIFFERENCE'
    _m.object = _c
    _c.hide_set(True)
    _c.hide_render = True
obj = _target

# step 6: lathe
mesh = bpy.data.meshes.new("lathe")
mesh.from_pydata([(0.792, 0.0, 8.04), (0.864, 0.0, 8.22), (1.08, 0.0, 8.34), (1.32, 0.0, 8.4)], [(0, 1), (1, 2), (2, 3)], [])
obj = bpy.data.objects.new("lathe", mesh)
bpy.context.collection.objects.link(obj)
bpy.context.view_layer.objects.active = obj
mod = obj.modifiers.new(name="Lathe", type='SCREW')
mod.angle = 6.283185307179586
mod.steps = 64
mod.use_merge_vertices = True
obj.location[2] = 0  # offset from drafted height

# step 7: cube
bpy.ops.mesh.primitive_cube_add(size=1.0)
obj = bpy.context.active_object
obj.scale = (2.64, 2.64, 0.24)
obj.location[2] = 8.52  # base z = 8.4

# step 8: cube
bpy.ops.mesh.primitive_cube_add(size=1.0)
obj = bpy.context.active_object
obj.scale = (3.36, 3.36, 0.96)
obj.location[2] = 9.12  # base z = 8.64
