recipe.id = "doric_column"
recipe.name = "Doric Column"
step.0.param.loc_z.value = "0"
step.0.param.size_x.value = "3"
step.0.param.size_y.value = "3"
step.0.param.size_z.value = "0.48"
step.0.shaper = "cube"
step.1.param.loc_z.value = "0.48"
step.1.param.size_x.value = "2.64"
step.1.param.size_y.value = "2.64"
step.1.param.size_z.value = "0.36"
step.1.shaper = "cube"
step.2.param.loc_z.value = "0"
step.2.param.segments.value = "64"
step.2.profile = "base_cove"
step.2.shaper = "lathe"
step.3.param.loc_z.value = "0"
step.3.param.segments.value = "64"
step.3.profile = "shaft"
step.3.shaper = "lathe"
step.4.param.at_radius.value = "1.056"
step.4.param.count.value = "20"
step.4.param.cutter_radius.value = "0.16"
step.4.param.depth.value = "0.12"
step.4.param.z_from.value = "1.2"
step.4.param.z_to.value = "6"
step.4.shaper = "radial_groove"
step.5.param.loc_z.value = "0"
step.5.param.segments.value = "64"
step.5.profile = "echinus"
step.5.shaper = "lathe"
step.6.param.loc_z.value = "8.4"
step.6.param.size_x.value = "2.64"
step.6.param.size_y.value = "2.64"
step.6.param.size_z.value = "0.24"
step.6.shaper = "cube"
step.7.param.loc_z.value = "8.64"
step.7.param.size_x.value = "3.36"
step.7.param.size_y.value = "3.36"
step.7.param.size_z.value = "0.96"
step.7.shaper = "cube"
