op.0.axis = "z"
op.0.entasis = "false"
op.0.entasis_ratio = "0.045"
op.0.height = "1.5"
op.0.material = "stone"
op.0.name = "column.circle"
op.0.radius = "0.75"
op.0.type = "AddCylinder"
op.0.vertices = "48"
op.0.x = "0"
op.0.y = "0"
op.0.z = "0.75"
op.0.z_mode = "center"
recipe.id = "circle_v0"
recipe.name = "Circle Column"
