op.0.base_z = "0"
op.0.footprint.0.x = "0"
op.0.footprint.0.y = "0"
op.0.footprint.1.x = "1.5"
op.0.footprint.1.y = "0"
op.0.footprint.2.x = "1.5"
op.0.footprint.2.y = "0.5"
op.0.footprint.3.x = "0.5"
op.0.footprint.3.y = "0.5"
op.0.footprint.4.x = "0.5"
op.0.footprint.4.y = "1.5"
op.0.footprint.5.x = "0"
op.0.footprint.5.y = "1.5"
op.0.height = "1.5"
op.0.inset = "0"
op.0.material = "stone"
op.0.name = "wall.corner_l"
op.0.normal_offset = "0"
op.0.taper_curve = "1"
op.0.taper_end = "1"
op.0.taper_end_y = "0"
op.0.type = "AddPrism"
op.0.x = "0"
op.0.y = "0"
recipe.id = "corner_l_v0"
recipe.name = "L Corner Wall"
