op.0.height = "0.5"
op.0.innerRadius = "0.4"
op.0.name = "girih.star"
op.0.outerRadius = "1"
op.0.points = "6"
op.0.script = "nfold_star"
op.0.skip = "5"
op.0.type = "Script"
op.0.x = "0"
op.0.y = "0"
op.0.z = "0"
recipe.id = "star6_v0"
recipe.name = "Six-Point Star"
