op.0.barkMat = "aged_stone"
op.0.branchLevels = "4"
op.0.childrenPerNode = "3"
op.0.clumpCount = "78"
op.0.clumpSize = "0.7"
op.0.height = "5.5"
op.0.leafMat = "sandstone"
op.0.name = "tree.c"
op.0.script = "tree"
op.0.seed = "3"
op.0.trunkRadius = "0.2"
op.0.type = "Script"
op.0.x = "0"
op.0.y = "0"
op.0.z = "0"
recipe.id = "tree_c_v0"
recipe.name = "Tree C (full + round)"
